plugins {
    id 'com.android.application'
}

android {
    signingConfigs {
        debug {
            storeFile file('C:\\Users\\User\\StudioProjects\\bmsdroid.jks')
            storePassword 'Aa123456'
            keyAlias 'bmsdroid'
            keyPassword 'Aa123456'
        }
    }
    namespace 'az.inci.hey_su_manage'

    defaultConfig {
        applicationId "az.inci.hey_su_manage"
        minSdk 26
        compileSdkVersion 36
        targetSdkVersion 36
        versionCode 22
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'com.squareup.okhttp3:okhttp:5.3.2'
    implementation 'com.google.code.gson:gson:2.13.2'
    implementation 'androidx.activity:activity:1.12.2'
    compileOnly(annotationProcessor 'org.projectlombok:lombok:1.18.30')
}